---
mastodon_app_version: 'v4.3.15'

federation:
  local_domain: 'example.com'
redis:
  hostname: 'localhost'
  port: '6379'
postgresql:
  hostname: '/var/run/postgresql'
  username: 'mastodon'
  db_name: 'mastodon_production'
  password: 'mastodon123'
  port: '5432'
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
elasticsearch:
  enabled: 'false'
  hostname: 'localhost'
  port: '9200'
  username: 'elastic'
  password: 'password'
smtp:
  server: ''
  port: '587'
  login: ''
  password: ''
  from_address: 'notifications@example.com'
s3:
  enabled: 'false'
  bucket: 'files.example.com'
  aws_access_key_id: ''
  aws_secret_access_key: ''
  alias_host: 'files.example.com'
