---
- name: Install nodenv
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/bin/anyenv install -s nodenv"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: "'Install nodenv succeeded!' in __result.stdout"
  register: __result
  retries: 3
  delay: 10
  until: __result is succeeded

- name: Verify node-build plugin installed
  ansible.builtin.stat:
    path: "{{ mastodon_app_anyenv_path }}/envs/nodenv/plugins/node-build"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  register: __result_node_build
  failed_when: not __result_node_build.stat.exists

- name: Update nodenv
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/bin/anyenv install --update nodenv"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: "'Install nodenv succeeded!' in __result.stdout"
  register: __result

- name: Get Node.js versions
  ansible.builtin.command:
    cmd: "{{ item.cmd }}"
  loop:
    - cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv install -l"
    - cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv global"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: false
  register: __result_node_versions

- name: Install Node.js
  ansible.builtin.command:
    cmd: "{{ item.cmd }}"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
    __version_nodejs: "{{ mastodon_node_version }}"
  loop:
    - cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv install -s {{ __version_nodejs }}"
    - cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv global {{ __version_nodejs }}"
  changed_when: "'Installed node' in __result.stderr"
  register: __result

- name: Upgrade npm
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/shims/npm install -U npm"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: false
  register: __result

- name: Install yarn via npm
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/shims/npm install -g yarn"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: "'added 1 package' in __result.stdout or 'updated 1 package' in __result.stdout"
  register: __result

- name: Rehash nodenv after yarn install
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv rehash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: false

- name: Enable corepack
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/shims/corepack enable"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: false
  register: __result

- name: Rehash nodenv after corepack enable
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/bin/nodenv rehash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: false

- name: Set yarn version to classic
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/nodenv/shims/yarn set version classic"
  environment:
    NODENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/nodenv"
    NODENV_SHELL: "bash"
  vars:
    ansible_become: true
    ansible_become_user: "{{ mastodon_app_user_name }}"
  changed_when: "'Switched to' in __result.stdout"
  register: __result
