---
- name: Manage PostgreSQL user
  block:
    - name: Create PostgreSQL user
      community.postgresql.postgresql_user:
        name: "{{ mastodon_db_user_name }}"
        password: "{{ mastodon_db_user_password }}"
        role_attr_flags: CREATEDB

    - name: Display PostgreSQL password
      ansible.builtin.debug:
        var: mastodon_db_user_password
  become: true
  become_user: postgres
